version: "3.6"
services:

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/key.json:ro
